### PR TITLE
add report_product.html.erb

### PR DESCRIPTION
**Pull request by zzrilakkuma**
123123

### CODE REVIEW

**Review by Weian0328 — COMMENTED** [review]
21321

**Review by Weian0328 — APPROVED** [review]

**Review by Weian0328 — APPROVED** [review]

**Review by cin-yi-wei — COMMENTED** [review]
ok

**Review by ChenKLi — APPROVED** [review]
check OK

**Review by zoechaoweiting — APPROVED** [review]
check ok!

**Review by cin-yi-wei — APPROVED** [review]
ok

**Pull request merged**
